database.py changed name to databas.py due to 'AttributeError: partially initialized module 'database' has no attribute 'Base' (most likely due to a circular import)'